# Use the official Golang image as the base image
FROM golang:1.23

# Set the working directory inside the container
WORKDIR /app

# Copy the source code into the container
COPY src/ .

# Build the Go application
# RUN go build -o app

# Expose the application's port
EXPOSE 8080

# Run the application
# CMD ["./app"]
