services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    command: ["/bin/sh", "-c", "go build -o main . && ./main"]
