version: '3.1'

services:
  php:
    build:
      context: ./
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./sources:/var/www/html/

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080
