version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 8001:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080
