services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src/php:/var/www/html
    depends_on:
      - mysql
      - rabbitmq
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "9000:80" # Локальный порт 9000 перенаправляется на порт 80 внутри контейнера Nginx
    volumes:
      - ./src/php:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - ./src/go:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
      - redis
    command: ["/bin/sh", "-c", "go build -o main . && ./main"]
    tty: true
    

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672"   # Основной порт
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  mysql_data:
