version: '3.1'

services:

  debian:
      build:
        context: ./
      ports:
        - "8888:80"
      volumes:
        - ./src:/src
      hostname: debian
      container_name: debian
      tty: true
