version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      # postgres root
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 9990:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9991:8080