version: '3.1'

services:

  debian:
      build:
        context: ./
        dockerfile: debian
      ports:
        - "8888:80"
      volumes:
        - ./files:/files
      hostname: debian
      tty: true
