version: '3'

networks:
    p1_network:
    
services:
    p1_debian_service:
        build:
            context: .
            dockerfile: ./debian/Dockerfile
        container_name: p1_debian
        ports:
            - "8980:80"
        volumes:
            - ./src:/app
            - ./html:/var/www/html
        tty: true
        networks:
            - p1_network

    p1_nginx_service:
        image: nginx:stable-alpine
        container_name: p1_nginx
        ports:
            - "8981:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/app
        networks:
            - p1_network
    
    p1_jenkins_service:
        image: jenkins/jenkins:lts
        container_name: p1_jenkins
        ports:
            - "8982:8080"
        volumes:
            - ./html:/html
        networks:
            - p1_network
