version: '3.1'

services:

  debian:
      build:
        context: ./
      ports:
        - "8888:80"
      volumes:
        - ./src:/src
      hostname: torizon
      container_name: torizon_os
      tty: true
